export const AUTH = "AUTH";
export const ISSIGNEDIN = "ISSIGNEDIN";
export const LOGOUT = "LOGOUT";

export const FETCH_TEACHERS = "FETCH_TEACHERS";
export const CREATE_TEACHER = "CREATE_TEACHER";
export const UPDATE_TEACHER = "UPDATE_TEACHER";
export const DELETE_TEACHER = "DELETE_TEACHER";

export const FETCH_STUDENTS = "FETCH_STUDENTS";
export const CREATE_STUDENT = "CREATE_STUDENT";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";

export const FETCH_SALARIES = "FETCH_SALARIES";
export const CREATE_SALARY = "CREATE_SALARY";
export const UPDATE_SALARY = "UPDATE_SALARY";
export const DELETE_SALARY = "DELETE_SALARY";

export const FETCH_TEACHERPAYMENTS = "FETCH_TEACHERPAYMENTS";
export const CREATE_TEACHERPAYMENT = "CREATE_TEACHERPAYMENT";
export const UPDATE_TEACHERPAYMENT = "UPDATE_TEACHERPAYMENT";
export const DELETE_TEACHERPAYMENT = "DELETE_TEACHERPAYMENT";

export const FETCH_EXPENSEOFMONTHSHEETS = "FETCH_EXPENSEOFMONTHSHEETS";
export const CREATE_EXPENSEOFMONTHSHEET = "CREATE_EXPENSEOFMONTHSHEET";
export const UPDATE_EXPENSEOFMONTHSHEET = "UPDATE_EXPENSEOFMONTHSHEET";
export const DELETE_EXPENSEOFMONTHSHEET = "DELETE_EXPENSEOFMONTHSHEET";

export const FETCH_TEACHERSALARYCHARTS = "FETCH_TEACHERSALARYCHARTS";
export const CREATE_TEACHERSALARYCHART = "CREATE_TEACHERSALARYCHART";
export const UPDATE_TEACHERSALARYCHART = "UPDATE_TEACHERSALARYCHART";
export const DELETE_TEACHERSALARYCHART = "DELETE_TEACHERSALARYCHART";

export const FETCH_CLASS = "FETCHCLASS";
export const CREATE_CLASS = "CREATE_CLASS";
export const UPDATE_CLASS = "UPDATE_CLASS";
export const DELETE_CLASS = "DELETE_CLASS";
